# Generated by Django 3.0.1 on 2020-04-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libuser',
            fields=[
                ('card_no', models.CharField(default=False, max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
